<a href="https://colab.research.google.com/github/Khushali-kavathiya/Python_Learning/blob/main/Essential_basic_functionality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.set_option("compute.use_bottleneck", False)

In [4]:
pd.set_option("compute.use_numexpr", False)

In [6]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

In [7]:
df

        one       two     three
a -0.372728  1.173469       NaN
b -2.280115  0.747961 -0.495376
c  0.123111  0.072402  1.466464
d       NaN  0.840659  0.982551

In [8]:
row = df.iloc[1]

In [10]:
row

one     -2.280115
two      0.747961
three   -0.495376
Name: b, dtype: float64

In [9]:
column = df["two"]

In [11]:
column

a    1.173469
b    0.747961
c    0.072402
d    0.840659
Name: two, dtype: float64

In [12]:
df.sub(row, axis="columns")

        one       two     three
a  1.907387  0.425508       NaN
b  0.000000  0.000000  0.000000
c  2.403225 -0.675559  1.961840
d       NaN  0.092699  1.477927

In [13]:
df.sub(column, axis="index")

        one  two     three
a -1.546197  0.0       NaN
b -3.028076  0.0 -1.243337
c  0.050709  0.0  1.394062
d       NaN  0.0  0.141891

In [14]:
df.sub(column, axis=0)

        one  two     three
a -1.546197  0.0       NaN
b -3.028076  0.0 -1.243337
c  0.050709  0.0  1.394062
d       NaN  0.0  0.141891

In [15]:
dfmi = df.copy()

In [20]:
dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "b"), (2, "a")], name=["first", "second"]
)

In [24]:
dfmi.sub(column, axis=1, level="second")

               a   b   c   d  one  three  two
first second
1     a      NaN NaN NaN NaN  NaN    NaN  NaN
      b      NaN NaN NaN NaN  NaN    NaN  NaN
      b      NaN NaN NaN NaN  NaN    NaN  NaN
2     a      NaN NaN NaN NaN  NaN    NaN  NaN

In [25]:
s = pd.Series(np.arange(10))

In [26]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [27]:
div, rem = divmod(s, 3)

In [28]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int64