<a href="https://colab.research.google.com/github/Khushali-kavathiya/Python_Learning/blob/main/Intro_to_data_structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
import numpy as np

# Series

In [ ]:
s = pd.Series(data, index=index)

From ndarray

If data is an ndarray, index must be the same length as data. If no index is passed, one will be created having values [0, ..., len(data) - 1].

In [5]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

In [6]:
s

a   -1.105085
b   -0.676642
c   -0.631160
d   -0.989679
e   -0.546413
dtype: float64

In [7]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [8]:
pd.Series(np.random.randn(5))

0   -1.981363
1    2.150057
2   -0.998019
3   -0.571589
4   -1.186195
dtype: float64

**From dict**

In [9]:
d = {"b": 1, "a": 0, "c": 2}

In [10]:
pd.Series(d)

b    1
a    0
c    2
dtype: int64

If an index is passed, the values in data corresponding to the labels in the index will be pulled out.

In [11]:
d = {"a": 0.0, "b": 1.0, "c": 2.0}

In [12]:
pd.Series(d)

a    0.0
b    1.0
c    2.0
dtype: float64

In [13]:
pd.Series(d, index=["b", "c", "d", "a"])

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

If data is a scalar value, the value will be repeated to match the length of index. If the index is not provided, it defaults to RangeIndex(1).

In [14]:
pd.Series(5.0, index=["a", "b", "c", "d", "e"])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

# Series is ndarray-like

Series acts very similarly to a numpy.ndarray and is a valid argument to most NumPy functions. However, operations such as slicing will also slice the index.

In [15]:
s.iloc[0]

np.float64(-1.1050853574990993)

In [16]:
s.iloc[:3]

a   -1.105085
b   -0.676642
c   -0.631160
dtype: float64

In [19]:
s[s > s.median()]

c   -0.631160
e   -0.546413
dtype: float64

In [20]:
s.iloc[[4,3,1]]

e   -0.546413
d   -0.989679
b   -0.676642
dtype: float64

In [21]:
np.exp(s)

a    0.331183
b    0.508321
c    0.531974
d    0.371696
e    0.579023
dtype: float64

In [22]:
s.dtype

dtype('float64')

In [23]:
s.array

<NumpyExtensionArray>
[np.float64(-1.1050853574990993), np.float64(-0.6766418619792333),
 np.float64(-0.6311601082854235), np.float64(-0.9896787244070578),
 np.float64(-0.5464133048318546)]
Length: 5, dtype: float64

In [24]:
s.to_numpy()

array([-1.10508536, -0.67664186, -0.63116011, -0.98967872, -0.5464133 ])

# Series is dict-like

A Series is also like a fixed-size dict in that you can get and set values by index label:

In [25]:
s["a"]

np.float64(-1.1050853574990993)

In [26]:
s["e"]

np.float64(-0.5464133048318546)

In [27]:
s

a   -1.105085
b   -0.676642
c   -0.631160
d   -0.989679
e   -0.546413
dtype: float64

In [28]:
"e" in s

True

In [29]:
"f" in s

False

Using the Series.get() method, a missing label will return None or specified default:

In [30]:
s.get("f")

In [31]:
s.get("f", np.nan)

nan

In [32]:
s+s

a   -2.210171
b   -1.353284
c   -1.262320
d   -1.979357
e   -1.092827
dtype: float64

In [33]:
s = pd.Series(np.random.randn(5), name="something")

In [34]:
s

0   -1.128519
1    0.989033
2   -0.532676
3    0.508338
4   -0.446442
Name: something, dtype: float64

In [35]:
s.name

'something'

 # From structured or record array

In [37]:
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "S10")])

In [38]:
data[:] = [(1, 2.0, "Hello"), (2, 3.0, "World")]

In [39]:
pd.DataFrame(data)

   A    B         C
0  1  2.0  b'Hello'
1  2  3.0  b'World'

# From a list of namedtuples

In [49]:
from collections import namedtuple

In [52]:
Point = namedtuple("Point", "x y")

In [53]:
pd.DataFrame([Point(0, 0), Point(0, 3), (2, 3)])

   x  y
0  0  0
1  0  3
2  2  3

In [54]:
Point3D = namedtuple("Point3D", "x y z")

In [55]:
pd.DataFrame([Point3D(0,0,0), Point3D(0,3,5), Point(2,3)])

   x  y    z
0  0  0  0.0
1  0  3  5.0
2  2  3  NaN